// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: display_server.proto
#ifndef GRPC_display_5fserver_2eproto__INCLUDED
#define GRPC_display_5fserver_2eproto__INCLUDED

#include "display_server.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace LED_display {

// service definition
class WS2801_Display final {
 public:
  static constexpr char const* service_full_name() {
    return "LED_display.WS2801_Display";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Make RPC on function DISPLAY_CHANGE with message DISPLAY_MSG
    // server response with DISPLAY_RESPONSE
    virtual ::grpc::Status DISPLAY_CHANGE(::grpc::ClientContext* context, const ::LED_display::DISPLAY_MSG& request, ::LED_display::DISPLAY_RESPONSE* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::LED_display::DISPLAY_RESPONSE>> AsyncDISPLAY_CHANGE(::grpc::ClientContext* context, const ::LED_display::DISPLAY_MSG& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::LED_display::DISPLAY_RESPONSE>>(AsyncDISPLAY_CHANGERaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::LED_display::DISPLAY_RESPONSE>> PrepareAsyncDISPLAY_CHANGE(::grpc::ClientContext* context, const ::LED_display::DISPLAY_MSG& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::LED_display::DISPLAY_RESPONSE>>(PrepareAsyncDISPLAY_CHANGERaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::LED_display::DISPLAY_RESPONSE>* AsyncDISPLAY_CHANGERaw(::grpc::ClientContext* context, const ::LED_display::DISPLAY_MSG& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::LED_display::DISPLAY_RESPONSE>* PrepareAsyncDISPLAY_CHANGERaw(::grpc::ClientContext* context, const ::LED_display::DISPLAY_MSG& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status DISPLAY_CHANGE(::grpc::ClientContext* context, const ::LED_display::DISPLAY_MSG& request, ::LED_display::DISPLAY_RESPONSE* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::LED_display::DISPLAY_RESPONSE>> AsyncDISPLAY_CHANGE(::grpc::ClientContext* context, const ::LED_display::DISPLAY_MSG& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::LED_display::DISPLAY_RESPONSE>>(AsyncDISPLAY_CHANGERaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::LED_display::DISPLAY_RESPONSE>> PrepareAsyncDISPLAY_CHANGE(::grpc::ClientContext* context, const ::LED_display::DISPLAY_MSG& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::LED_display::DISPLAY_RESPONSE>>(PrepareAsyncDISPLAY_CHANGERaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::LED_display::DISPLAY_RESPONSE>* AsyncDISPLAY_CHANGERaw(::grpc::ClientContext* context, const ::LED_display::DISPLAY_MSG& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::LED_display::DISPLAY_RESPONSE>* PrepareAsyncDISPLAY_CHANGERaw(::grpc::ClientContext* context, const ::LED_display::DISPLAY_MSG& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DISPLAY_CHANGE_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Make RPC on function DISPLAY_CHANGE with message DISPLAY_MSG
    // server response with DISPLAY_RESPONSE
    virtual ::grpc::Status DISPLAY_CHANGE(::grpc::ServerContext* context, const ::LED_display::DISPLAY_MSG* request, ::LED_display::DISPLAY_RESPONSE* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_DISPLAY_CHANGE : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_DISPLAY_CHANGE() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DISPLAY_CHANGE() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DISPLAY_CHANGE(::grpc::ServerContext* context, const ::LED_display::DISPLAY_MSG* request, ::LED_display::DISPLAY_RESPONSE* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDISPLAY_CHANGE(::grpc::ServerContext* context, ::LED_display::DISPLAY_MSG* request, ::grpc::ServerAsyncResponseWriter< ::LED_display::DISPLAY_RESPONSE>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DISPLAY_CHANGE<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_DISPLAY_CHANGE : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_DISPLAY_CHANGE() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DISPLAY_CHANGE() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DISPLAY_CHANGE(::grpc::ServerContext* context, const ::LED_display::DISPLAY_MSG* request, ::LED_display::DISPLAY_RESPONSE* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DISPLAY_CHANGE : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_DISPLAY_CHANGE() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::LED_display::DISPLAY_MSG, ::LED_display::DISPLAY_RESPONSE>(std::bind(&WithStreamedUnaryMethod_DISPLAY_CHANGE<BaseClass>::StreamedDISPLAY_CHANGE, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_DISPLAY_CHANGE() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DISPLAY_CHANGE(::grpc::ServerContext* context, const ::LED_display::DISPLAY_MSG* request, ::LED_display::DISPLAY_RESPONSE* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDISPLAY_CHANGE(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::LED_display::DISPLAY_MSG,::LED_display::DISPLAY_RESPONSE>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_DISPLAY_CHANGE<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_DISPLAY_CHANGE<Service > StreamedService;
};

}  // namespace LED_display


#endif  // GRPC_display_5fserver_2eproto__INCLUDED
